import = ["/home/rickoh/.config/alacritty/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[font.bold]
family = "Caskaydia Cove Nerd Font"
style = "Bold"

[font.italic]
family = "Caskaydia Cove Nerd Font"
style = "Italic"

[font.normal]
family = "Caskaydia Cove Nerd Font"
style = "Regular"

[window]
decorations_theme_variant = "Dark"
opacity = 0.9
